### PR TITLE
feat(mongosh): Add mongosh command

### PR DESCRIPTION
**Pull request by julienloizelet**
## The Issue

[mongosh](https://www.mongodb.com/docs/mongodb-shell/) is not present as a ddev command and I guess it could be useful.

## How This PR Solves The Issue

This PR add the `ddev mongosh` command

## Manual Testing Instructions

Start a project with this add-on.

Run `ddev mongosh`

### CODE REVIEW

**Review by rfay — COMMENTED** [review]
How about adding a test to make sure it's working?

**Comment by julienloizelet** [comment]
> How about adding a test to make sure it's working?

Sure, I will add some test asap. Thanks.

**Comment by rfay** [comment]
Since you're a mongo user, would you consider becoming a maintainer of this add-on?

**Comment by julienloizelet** [comment]
> Since you're a mongo user, would you consider becoming a maintainer of this add-on?

Yes, I guess I can do it. 

Please invite me to this repo and I could prepare the next release.

(I just added tests for mongosh too)

**Comment by rfay** [comment]
I guess you'd already been invited, maybe we talked about this before. Anyway, I sent the invitation again, check your email.

**Comment by tyler36** [comment]
I sent the invite about 5 mins after @julienloizelet said yes.

**Comment by rfay** [comment]
> I sent the invite about 5 mins after @julienloizelet said yes.

That's it then! :)

**Comment by julienloizelet** [comment]
Thanks @rfay and @tyler36 :) 

Tests are failing here because mongosh is not present on the last release.

Can we merge this ?

**Comment by tyler36** [comment]
> ok 1 install from directory

Seems to be passing from "install from directory" so it should be good to merge and create a release.

**Comment by julienloizelet** [comment]
> > ok 1 install from directory
> 
> Seems to be passing from "install from directory" so it should be good to merge and create a release.

Ok, I will do that asap (tomorrow I guess). Thanks.

**Comment by rfay** [comment]
Yes, it's OK to merge. The other thing we do sometimes is disable the "install from release" temporarily. But you're paying attention and will fix everything so it can be done any way you like.

**Pull request merged**
